In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/playground-series-s6e2/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e2/train.csv
/kaggle/input/competitions/playground-series-s6e2/test.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e2/train.csv')

In [4]:
df.shape

(630000, 15)

In [5]:
df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [6]:
df.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,54.136706,0.714735,3.312752,130.497433,245.011814,0.079987,0.981660,152.816763,0.273725,0.716028,1.455871,0.451040,4.618873
std,181865.479132,8.256301,0.451541,0.851615,14.975802,33.681581,0.271274,0.998783,19.112927,0.445870,0.948472,0.545192,0.798549,1.950007
min,0.000000,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,157499.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,314999.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.000000,3.000000
75%,472499.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.000000,7.000000
max,629999.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Age                      630000 non-null  int64
 2   Sex                      630000 non-null  int64
 3   Chest pain type          630000 non-null  int64
 4   BP                       630000 non-null  int64
 5   Cholesterol              630000 non-null  int64
 6   FBS over 120             630000 non-null  int64
 7   EKG results              630000 non-null  int64
 8   Max HR                   630000 non-null  int64
 9   Exercise angina          630000 non-null  int64
 10  ST depression            630000 non-null  float64
 11  Slope of ST              630000 non-null  int64
 12  Number of vessels fluro  630000 non-null  int64
 13  Thallium                 630000 non-null  int64
 14  Heart Disease            630000 non-null  object
dtypes: float64(1), int64(13), object(1)
memory usage: 72.1+ MB

In [8]:
df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [9]:
# Categorical Colms

In [10]:
df['FBS over 120'].value_counts()

FBS over 120
0    579608
1     50392
Name: count, dtype: int64

In [11]:
df['Chest pain type'].value_counts()

Chest pain type
4    329179
3    197278
2     74941
1     28602
Name: count, dtype: int64

In [12]:
df['EKG results'].value_counts()

EKG results
0    320116
2    308562
1      1322
Name: count, dtype: int64

In [13]:
df['Slope of ST'].value_counts()

Slope of ST
1    358293
2    256215
3     15492
Name: count, dtype: int64

In [14]:
df['Number of vessels fluro'].value_counts()

Number of vessels fluro
0    445862
1    106978
2     54303
3     22857
Name: count, dtype: int64

In [15]:
df['Thallium'].value_counts()

Thallium
3    372286
7    246748
6     10966
Name: count, dtype: int64

In [16]:
df['Heart Disease'] = df['Heart Disease'].map({'Presence':1,'Absence':0})

In [17]:
df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,1
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,0
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,0
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,0
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,1

In [18]:
X=df.drop(['id','Heart Disease'],axis=1)
y=df['Heart Disease']

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,test_size=0.2,random_state=42)

In [20]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
encoder = OneHotEncoder()

categorical_colms_train = ['Chest pain type','EKG results','Slope of ST','Number of vessels fluro',
                            'Thallium']
num_columns = ['Age','BP','Cholesterol','Max HR','ST depression']

ct = ColumnTransformer([('encoder',encoder,categorical_colms_train),
                       ('scaler',scaler,num_columns)],remainder = 'passthrough')
X_train_transformed = ct.fit_transform(X_train)
X_val_transformed = ct.transform(X_val)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
log = LogisticRegression()
log.fit(X_train_transformed,y_train)
log_pred = log.predict(X_val_transformed)

In [22]:
log_train_pred = log.predict(X_train_transformed)
print(accuracy_score(log_train_pred
                     ,y_train))

0.8851507936507936

In [23]:
print(accuracy_score(log_pred
                     ,y_val))

0.8870317460317461

In [24]:
print("Train Report:\n", classification_report(y_train, log_train_pred))
print("Validation Report:\n", classification_report(y_val, log_pred))

Train Report:
               precision    recall  f1-score   support

           0       0.89      0.91      0.90    278037
           1       0.88      0.86      0.87    225963

    accuracy                           0.89    504000
   macro avg       0.88      0.88      0.88    504000
weighted avg       0.89      0.89      0.89    504000

Validation Report:
               precision    recall  f1-score   support

           0       0.89      0.91      0.90     69509
           1       0.88      0.86      0.87     56491

    accuracy                           0.89    126000
   macro avg       0.89      0.88      0.89    126000
weighted avg       0.89      0.89      0.89    126000

In [25]:
print("Validation Confusion Matrix:\n", confusion_matrix(y_val, log_pred))

Validation Confusion Matrix:
 [[63116  6393]
 [ 7841 48650]]

In [26]:
from sklearn.metrics import roc_auc_score

y_train_proba = log.predict_proba(X_train_transformed)[:,1]
y_val_proba = log.predict_proba(X_val_transformed)[:,1]

print("Train ROC-AUC:", roc_auc_score(y_train, y_train_proba))
print("Validation ROC-AUC:", roc_auc_score(y_val, y_val_proba))

Train ROC-AUC: 0.9526836085739918
Validation ROC-AUC: 0.9536968945784973

In [27]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train_transformed,y_train)
train_pred = clf.predict(X_train_transformed)
val_pred = clf.predict(X_val_transformed)

In [28]:
print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Validation Accuracy:", accuracy_score(y_val, val_pred))

Train Accuracy: 0.9999781746031746
Validation Accuracy: 0.8813888888888889

In [29]:
print("Train Report:\n", classification_report(y_train, train_pred))
print("Validation Report:\n", classification_report(y_val, val_pred))

Train Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    278037
           1       1.00      1.00      1.00    225963

    accuracy                           1.00    504000
   macro avg       1.00      1.00      1.00    504000
weighted avg       1.00      1.00      1.00    504000

Validation Report:
               precision    recall  f1-score   support

           0       0.89      0.90      0.89     69509
           1       0.87      0.86      0.87     56491

    accuracy                           0.88    126000
   macro avg       0.88      0.88      0.88    126000
weighted avg       0.88      0.88      0.88    126000

In [30]:
clf_train_proba = clf.predict_proba(X_train_transformed)[:,1]
clf_val_proba = clf.predict_proba(X_val_transformed)[:,1]

print("Train ROC-AUC:", roc_auc_score(y_train, clf_train_proba))
print("Validation ROC-AUC:", roc_auc_score(y_val, clf_val_proba))

Train ROC-AUC: 0.9999999968484423
Validation ROC-AUC: 0.9468380237455042

In [31]:
test_data = pd.read_csv('/kaggle/input/competitions/playground-series-s6e2/test.csv')

In [32]:
test_data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

In [33]:
test_ids = test_data['id']
X_test = test_data.drop('id',axis=1)
X_test_transformed = ct.transform(X_test)
test_proba = log.predict_proba(X_test_transformed)[:, 1]
submission = pd.DataFrame({'id': test_ids,
    'Heart Disease': test_proba
})
submission.to_csv('submission.csv', index=False)